# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clauses_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc',
            field=models.FileField(blank=True, upload_to=b'pdf_folder'),
        ),
    ]
